apiVersion: v1
kind: Service
metadata:
  name: ngp-postgres
  labels:
    app: ngp-postgres
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 5432
      name: http
  selector:
   app: ngp-postgres



