{{- if .Values.services.dssServicePostgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dssServiceApplication.postgres.appName }}
  labels:
    app: {{ .Values.dssServiceApplication.postgres.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dssServiceApplication.postgres.appName }}
  template:
    metadata:      
      labels:
        app: {{ .Values.dssServiceApplication.postgres.appName }}
    spec:
      containers:
        - name: {{ .Values.dssServiceApplication.postgres.appName }}
          image: {{ .Values.dssServiceApplication.postgres.image }}
          imagePullPolicy: {{ .Values.dssServiceApplication.postgres.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.dssServiceApplication.postgres.ports.targetPort }}
              name: {{ .Values.dssServiceApplication.postgres.ports.name }}
          
          env:
          - name: POSTGRES_DB
            value: datascienceapi
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
{{- end -}}