apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngp-postgres
  labels:
    app: ngp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngp-postgres
  template:
    metadata:      
      labels:
        app: ngp-postgres
    spec:
      containers:
        - name: ngp-postgres
          image: postgres:9.6.14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: http
          
          env:
          - name: POSTGRES_DB
            value: datascienceapi
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres