{{- if .Values.services.dssServicePostgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dssServiceApplication.postgres.appName }}
  labels:
    app: {{ .Values.dssServiceApplication.postgres.appName }}
spec:
  type: {{ .Values.dssServiceApplication.postgres.type }}
  ports:
    - port: {{ .Values.dssServiceApplication.postgres.ports.port }}
      targetPort: {{ .Values.dssServiceApplication.postgres.ports.targetPort }}
      name: {{ .Values.dssServiceApplication.postgres.ports.name }}
  selector:
   app: {{ .Values.dssServiceApplication.postgres.appName }}
{{- end -}}


