{{- if .Values.services.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name}}
  namespace: {{ .Values.tenant }}
  labels:
    app: {{ .Values.postgres.name}}
spec:
  type: {{ .Values.postgres.type }}
  ports:
    - port: {{ .Values.postgres.ports.containerPort }}
      name: {{ .Values.postgres.ports.name }}
  selector:
   app: {{ .Values.postgres.name}}
{{- end -}}



